name: 09c - Artefactos
 
on:
 
  workflow_dispatch:
    # inputs:
    #   numero-dados:
    #     type: choice
    #     options:
    #       - uno
    #       - dos
    #     default: dos
    #     description: El número de dados
jobs:
  tirada-dados:
    runs-on: ubuntu-latest
    steps:
      - name: Generar numeros de dados
        run: |
          echo "Dado 1: $((1 + RANDOM % 6))" > dato1.txt
          echo "Dado 2: $((1 + RANDOM % 6))" > dato2.txt
      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: dados
          path: |
            dato1.txt
            dato2.txt
  
  imprimir-dados:
    runs-on: ubuntu-latest
    needs: tirada-dados
    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
            name: dados
      - name: Imprimir dados
        run: |
          cat ${{ github.workspace }}/dados/dato1.txt >> $GITHUB_STEP_SUMMARY
          cat ${{ github.workspace }}/dados/dato2.txt >> $GITHUB_STEP_SUMMARY

      

        

